-- Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
-- SPDX-License-Identifier: Apache-2.0
-- GENERATED by scripts/generate_sample_data.py — do not edit by hand.

INSERT INTO documents (doc_id, domain, doc_type, num_pages, title) VALUES
    ('nist_ai_rmf', 'artificial_intelligence', 'framework', 48, 'AI Risk Management Framework (NIST AI 100-1)'),
    ('nist_cybersecurity_framework', 'cybersecurity', 'framework', 32, 'Cybersecurity Framework 2.0 (NIST CSWP 29)'),
    ('eia_annual_energy_outlook_2023', 'energy', 'report', 50, 'Annual Energy Outlook 2023 (U.S. EIA)'),
    ('nces_education_report_2023', 'education', 'report', 54, 'NCES Education Report 2023-144');
