frontend:
  - changed-files:
      - any-glob-to-any-file: "samples/**/frontend/**"

infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          - "samples/**/infra-cdk/**"
          - "samples/**/infra-terraform/**"

backend:
  - changed-files:
      - any-glob-to-any-file:
          - "samples/**/gateway/**"
          - "samples/**/patterns/**"
          - "samples/**/tools/**"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "samples/**/docs/**"
          - "**/*.md"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - "samples/**/tests/**"
          - "samples/**/test-scripts/**"
          - "**/*.test.*"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "samples/**/docker/**"
          - "**/Dockerfile*"
