# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Chat Sessions index API Lambda Handler.

Maintains the per-user "table of contents" of chat sessions (the sidebar list)
in DynamoDB, separately from the conversation body (which lives in AgentCore
Memory). The ``actorId`` is ALWAYS the Cognito ``sub`` from the validated JWT
(authorizer claims), never from the request body.

DynamoDB schema (table <stack>-chat-sessions):
  pk = "USER#<sub>"
  sk = "<createdAt_iso8601>#<sessionId>"   # ISO time sorts chronologically;
                                            # sessionId suffix avoids same-ms collisions
  attrs: sessionId, title, createdAt, lastMessageAt

Endpoints:
  GET  /sessions
    -> 200 {"sessions": [{id, name, createdAt}, ...]}  # newest first
  POST /sessions   body: {sessionId, firstUserMessage}
    -> 200 {"sessionId", "title", "createdAt"}
       Idempotent: an existing sessionId is returned as-is (no regeneration),
       so a double-fire from the frontend is safe. The title is generated by
       Bedrock Haiku (Converse) summarising the first user message; on any
       failure we fall back to a truncation of that message so the call always
       succeeds (the title is a UX aid and must never block the conversation).
       An over-long firstUserMessage is truncated, never rejected, for the same
       reason -- the leading text is all the title needs.
"""

import os
import time
from typing import Any, Dict, List, Optional

import boto3
from aws_lambda_powertools import Logger, Tracer
from aws_lambda_powertools.event_handler import APIGatewayRestResolver, CORSConfig
from aws_lambda_powertools.logging.correlation_paths import API_GATEWAY_REST
from aws_lambda_powertools.utilities.typing import LambdaContext
from botocore.exceptions import ClientError
from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel

# Environment variables
TABLE_NAME = os.environ["TABLE_NAME"]
HAIKU_MODEL_ID = os.environ["HAIKU_MODEL_ID"]
CORS_ALLOWED_ORIGINS = os.environ.get("CORS_ALLOWED_ORIGINS", "*")

MAX_SESSION_ID_LENGTH = 100
# The first user message is truncated to this many characters before it reaches
# Haiku. The title only needs the leading text, so this caps the prompt cost
# without ever rejecting a long message (which would block the title -- a UX aid
# that must never fail the conversation).
FIRST_MESSAGE_TRUNCATE_LENGTH = 5000
# Fallback title length when Haiku is unavailable.
FALLBACK_TITLE_LENGTH = 40
# Sidebar list page size.
LIST_LIMIT = 50

# Parse CORS origins (mirrors feedback Lambda).
cors_origins = [
    origin.strip() for origin in CORS_ALLOWED_ORIGINS.split(",") if origin.strip()
]
primary_origin = cors_origins[0] if cors_origins else "*"
extra_origins = cors_origins[1:] if len(cors_origins) > 1 else None

cors_config = CORSConfig(
    allow_origin=primary_origin,
    extra_origins=extra_origins,
    allow_headers=["Content-Type", "Authorization"],
    allow_credentials=True,
)

dynamodb = boto3.client("dynamodb")
bedrock_runtime = boto3.client("bedrock-runtime")

tracer = Tracer()
logger = Logger()
app = APIGatewayRestResolver(cors=cors_config)

_TITLE_SYSTEM_PROMPT = (
    "You write a short, descriptive title for a chat conversation, like a blog "
    "post headline. Reply with ONLY the title text: no quotes, no punctuation at "
    "the end, at most 8 words. Match the language of the conversation."
)


class CreateSessionRequest(BaseModel):
    """POST /sessions request body (accepts camelCase from the client).

    first_user_message has no max_length on purpose: an over-long message is
    truncated in the handler, never rejected, so a long first question can never
    block title generation. It is the only field used to build the title.
    """

    model_config = ConfigDict(alias_generator=to_camel, populate_by_name=True)

    session_id: str = Field(..., min_length=1, max_length=MAX_SESSION_ID_LENGTH)
    first_user_message: str = Field(..., min_length=1)


def _get_actor_id() -> Optional[str]:
    """Return the Cognito sub from the authorizer claims, or None if absent."""
    request_context = app.current_event.request_context
    authorizer = request_context.authorizer
    claims = authorizer.get("claims", {}) if authorizer else {}
    return claims.get("sub") if claims else None


def _fallback_title(first_user_message: str) -> str:
    """Truncate the first user message as a title when Haiku is unavailable."""
    text = first_user_message.strip().replace("\n", " ")
    if len(text) > FALLBACK_TITLE_LENGTH:
        return f"{text[:FALLBACK_TITLE_LENGTH]}…"
    return text


def _generate_title(first_user_message: str) -> str:
    """Generate a blog-style title via Bedrock Haiku, falling back on any error."""
    conversation = f"User: {first_user_message}"
    try:
        response = bedrock_runtime.converse(
            modelId=HAIKU_MODEL_ID,
            system=[{"text": _TITLE_SYSTEM_PROMPT}],
            messages=[{"role": "user", "content": [{"text": conversation}]}],
            inferenceConfig={"maxTokens": 40, "temperature": 0.2},
        )
        text = response["output"]["message"]["content"][0]["text"].strip()
        # Strip wrapping quotes the model may add despite instructions.
        text = text.strip('"').strip("'").strip()
        return text or _fallback_title(first_user_message)
    except Exception as e:
        logger.warning(f"Haiku title generation failed, using fallback: {e}")
        return _fallback_title(first_user_message)


@app.get("/sessions")
def list_sessions() -> Dict[str, Any]:
    """Handle GET /sessions — return the user's session list, newest first."""
    actor_id = _get_actor_id()
    if not actor_id:
        return {"error": "Unauthorized"}, 401

    try:
        response = dynamodb.query(
            TableName=TABLE_NAME,
            KeyConditionExpression="pk = :pk",
            ExpressionAttributeValues={":pk": {"S": f"USER#{actor_id}"}},
            ScanIndexForward=False,  # newest first (SK starts with ISO timestamp)
            Limit=LIST_LIMIT,
        )
        sessions: List[Dict[str, str]] = [
            {
                "id": item["sessionId"]["S"],
                "name": item.get("title", {}).get("S", ""),
                "createdAt": item.get("createdAt", {}).get("S", ""),
            }
            for item in response.get("Items", [])
        ]
        return {"sessions": sessions}
    except ClientError as e:
        logger.error(f"DynamoDB error: {e.response['Error']['Message']}")
        return {"error": "Internal server error"}, 500
    except Exception as e:
        logger.error(f"Error listing sessions: {str(e)}")
        return {"error": "Internal server error"}, 500


@app.post("/sessions")
def create_session() -> Dict[str, Any]:
    """Handle POST /sessions — create the index entry with a generated title."""
    actor_id = _get_actor_id()
    if not actor_id:
        return {"error": "Unauthorized"}, 401

    try:
        body = CreateSessionRequest(**app.current_event.json_body)
    except ValueError as e:
        logger.warning(f"Validation error: {str(e)}")
        return {"error": str(e)}, 400

    if not body.session_id.replace("-", "").replace("_", "").isalnum():
        return {"error": "sessionId has invalid characters"}, 400

    pk = f"USER#{actor_id}"

    # Idempotency: if this session is already indexed, return it unchanged so a
    # double-fire (React StrictMode / retry) does not regenerate the title.
    try:
        existing = dynamodb.query(
            TableName=TABLE_NAME,
            KeyConditionExpression="pk = :pk",
            FilterExpression="sessionId = :sid",
            ExpressionAttributeValues={
                ":pk": {"S": pk},
                ":sid": {"S": body.session_id},
            },
            Limit=1,
        )
        items = existing.get("Items", [])
        if items:
            item = items[0]
            return {
                "sessionId": body.session_id,
                "title": item.get("title", {}).get("S", ""),
                "createdAt": item.get("createdAt", {}).get("S", ""),
            }
    except ClientError as e:
        logger.error(f"DynamoDB query error: {e.response['Error']['Message']}")
        return {"error": "Internal server error"}, 500

    # Truncate before Haiku: the title needs only the leading text, and an
    # over-long message must not block (or inflate) title generation.
    title = _generate_title(body.first_user_message[:FIRST_MESSAGE_TRUNCATE_LENGTH])
    # ISO8601 UTC with millisecond precision; sorts chronologically as the SK prefix.
    now_ms = int(time.time() * 1000)
    created_at = (
        time.strftime("%Y-%m-%dT%H:%M:%S", time.gmtime(now_ms / 1000))
        + f".{now_ms % 1000:03d}Z"
    )
    sk = f"{created_at}#{body.session_id}"

    try:
        dynamodb.put_item(
            TableName=TABLE_NAME,
            Item={
                "pk": {"S": pk},
                "sk": {"S": sk},
                "sessionId": {"S": body.session_id},
                "title": {"S": title},
                "createdAt": {"S": created_at},
                "lastMessageAt": {"S": created_at},
            },
        )
    except ClientError as e:
        logger.error(f"DynamoDB put error: {e.response['Error']['Message']}")
        return {"error": "Internal server error"}, 500

    return {"sessionId": body.session_id, "title": title, "createdAt": created_at}


@logger.inject_lambda_context(correlation_id_path=API_GATEWAY_REST)
def handler(event: dict, context: LambdaContext) -> dict:
    """Lambda handler for the chat sessions API."""
    return app.resolve(event, context)
