#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

"""Single source of truth for the sample dataset.

The sample uses a few real, multi-domain PDF documents that are U.S. government
publications in the public domain (see README for sources). The PDFs are NOT
stored in this repository: this script downloads them from their official .gov
sources. From one definition this emits:

  1. data/documents/<file>.pdf                 -> downloaded source document
  2. data/documents/<file>.pdf.metadata.json  -> Bedrock KB metadata sidecar
  3. infra-cdk/lambdas/db-seed/seed.sql        -> the structured `documents` table

The KB metadata keys equal the Postgres columns and doc_id links the two stores,
so the same filters (domain, num_pages, doc_type) work across doc_search
(unstructured) and structured_search (structured). doc_id is the PDF filename stem.

Run this BEFORE `cdk deploy` (the Knowledge Base ingests data/documents at deploy):

    python3 scripts/generate_sample_data.py
"""

import json
import os
import urllib.request

# (pdf_filename, domain, doc_type, num_pages, title, source_url)
DOCUMENTS = [
    (
        "nist_ai_rmf.pdf",
        "artificial_intelligence",
        "framework",
        48,
        "AI Risk Management Framework (NIST AI 100-1)",
        "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf",
    ),
    (
        "nist_cybersecurity_framework.pdf",
        "cybersecurity",
        "framework",
        32,
        "Cybersecurity Framework 2.0 (NIST CSWP 29)",
        "https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf",
    ),
    (
        "eia_annual_energy_outlook_2023.pdf",
        "energy",
        "report",
        50,
        "Annual Energy Outlook 2023 (U.S. EIA)",
        "https://www.eia.gov/outlooks/aeo/pdf/AEO2023_Narrative.pdf",
    ),
    (
        "nces_education_report_2023.pdf",
        "education",
        "report",
        54,
        "NCES Education Report 2023-144",
        "https://nces.ed.gov/pubs2023/2023144.pdf",
    ),
]

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SEED_SQL = os.path.join(REPO, "infra-cdk", "lambdas", "db-seed", "seed.sql")
DOCS_DIR = os.path.join(REPO, "data", "documents")


def doc_id_of(filename: str) -> str:
    return filename.rsplit(".", 1)[0]


def sql_escape(text: str) -> str:
    return text.replace("'", "''")


def write_seed_sql() -> None:
    lines = [
        "-- Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.",
        "-- SPDX-License-Identifier: Apache-2.0",
        "-- GENERATED by scripts/generate_sample_data.py — do not edit by hand.",
        "",
        "INSERT INTO documents (doc_id, domain, doc_type, num_pages, title) VALUES",
    ]
    rows = [
        f"    ('{doc_id_of(f)}', '{domain}', '{doc_type}', {pages}, '{sql_escape(title)}')"
        for (f, domain, doc_type, pages, title, _url) in DOCUMENTS
    ]
    lines.append(",\n".join(rows) + ";")
    lines.append("")
    with open(SEED_SQL, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {SEED_SQL}")


def download_documents() -> None:
    """Download the source PDFs from their official .gov URLs (skips existing files)."""
    os.makedirs(DOCS_DIR, exist_ok=True)
    for filename, _domain, _doc_type, _pages, _title, url in DOCUMENTS:
        path = os.path.join(DOCS_DIR, filename)
        if os.path.exists(path) and os.path.getsize(path) > 0:
            print(f"exists  {filename} (skipping)")
            continue
        print(f"downloading {filename} from {url} ...")
        # Some .gov servers reject requests without a browser-like User-Agent.
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=120) as resp:  # nosec B310 - fixed https:// .gov URLs
            data = resp.read()
        if not data.startswith(b"%PDF"):
            raise RuntimeError(f"{url} did not return a PDF (got {data[:16]!r})")
        with open(path, "wb") as fh:
            fh.write(data)
        print(f"wrote   {filename} ({len(data)} bytes)")


def write_sidecars() -> None:
    for filename, domain, doc_type, pages, title, _url in DOCUMENTS:
        sidecar = {
            "metadataAttributes": {
                "doc_id": doc_id_of(filename),
                "domain": domain,
                "doc_type": doc_type,
                "num_pages": pages,
                "title": title,
            }
        }
        path = os.path.join(DOCS_DIR, f"{filename}.metadata.json")
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(sidecar, fh, indent=2)
    print(f"wrote {len(DOCUMENTS)} metadata sidecars to {DOCS_DIR}")


if __name__ == "__main__":
    download_documents()
    write_seed_sql()
    write_sidecars()
